//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BomeansPCTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BomeansPCTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ALL_CATEGORY {
            get {
                return ResourceManager.GetString("ALL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_all {
            get {
                object obj = ResourceManager.GetObject("delete_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete1 {
            get {
                object obj = ResourceManager.GetObject("delete1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down {
            get {
                object obj = ResourceManager.GetObject("down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed!
        ///You may need to run the download again..
        /// </summary>
        internal static string E_DOWNLOAD_FAILED {
            get {
                return ResourceManager.GetString("E_DOWNLOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is empty!.
        /// </summary>
        internal static string E_EMPTY_APIKEY {
            get {
                return ResourceManager.GetString("E_EMPTY_APIKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}!.
        /// </summary>
        internal static string E_FAILED_TO_LOAD_FROM {
            get {
                return ResourceManager.GetString("E_FAILED_TO_LOAD_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save to {0}!.
        /// </summary>
        internal static string E_FAILED_TO_SAVE_TO {
            get {
                return ResourceManager.GetString("E_FAILED_TO_SAVE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No learning data!.
        /// </summary>
        internal static string E_NO_LEARNING_DATA {
            get {
                return ResourceManager.GetString("E_NO_LEARNING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid learning data to save!.
        /// </summary>
        internal static string E_NO_LEARNING_DATA_TO_SAVE {
            get {
                return ResourceManager.GetString("E_NO_LEARNING_DATA_TO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a key entry first..
        /// </summary>
        internal static string E_NO_SELECTED_KEY {
            get {
                return ResourceManager.GetString("E_NO_SELECTED_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop learning first!.
        /// </summary>
        internal static string E_STOP_LEARNING_FIRST {
            get {
                return ResourceManager.GetString("E_STOP_LEARNING_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IrEasy is not connected!.
        /// </summary>
        internal static string E_UART_NOT_OPEN {
            get {
                return ResourceManager.GetString("E_UART_NOT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download is cancelled!.
        /// </summary>
        internal static string E_USER_CANCELLED {
            get {
                return ResourceManager.GetString("E_USER_CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eye {
            get {
                object obj = ResourceManager.GetObject("eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMS Files(*.bms)|*.bms|All Files(*.*)|*.*.
        /// </summary>
        internal static string FILTER_BMS {
            get {
                return ResourceManager.GetString("FILTER_BMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Key List.
        /// </summary>
        internal static string I_DOWNLOAD_KEYLIST {
            get {
                return ResourceManager.GetString("I_DOWNLOAD_KEYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Brands....
        /// </summary>
        internal static string I_DOWNLOADING_BRANDS {
            get {
                return ResourceManager.GetString("I_DOWNLOADING_BRANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading IR Formats....
        /// </summary>
        internal static string I_DOWNLOADING_FORMATS {
            get {
                return ResourceManager.GetString("I_DOWNLOADING_FORMATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Keys....
        /// </summary>
        internal static string I_DOWNLOADING_KEYS {
            get {
                return ResourceManager.GetString("I_DOWNLOADING_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Types....
        /// </summary>
        internal static string I_DOWNLOADING_TYPES {
            get {
                return ResourceManager.GetString("I_DOWNLOADING_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_folder {
            get {
                object obj = ResourceManager.GetObject("open_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel download? Program may not work properly..
        /// </summary>
        internal static string Q_CONFIRM_CANCELLATION {
            get {
                return ResourceManager.GetString("Q_CONFIRM_CANCELLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all learning data?.
        /// </summary>
        internal static string Q_DELETE_ALL_LEARNING_DATA {
            get {
                return ResourceManager.GetString("Q_DELETE_ALL_LEARNING_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to provide API Key first!
        ///
        ///Setup it now?.
        /// </summary>
        internal static string Q_SETUP_API {
            get {
                return ResourceManager.GetString("Q_SETUP_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IrEasy is in learning mode!
        ///
        ///Stop learning mode now?.
        /// </summary>
        internal static string Q_STOP_LEARNING_NOW {
            get {
                return ResourceManager.GetString("Q_STOP_LEARNING_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_mark {
            get {
                object obj = ResourceManager.GetObject("question_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Learning.
        /// </summary>
        internal static string START_LEARNING {
            get {
                return ResourceManager.GetString("START_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Learning.
        /// </summary>
        internal static string STOP_LEARNING {
            get {
                return ResourceManager.GetString("STOP_LEARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Code.
        /// </summary>
        internal static string TITLE_CUSTOM_CODE {
            get {
                return ResourceManager.GetString("TITLE_CUSTOM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IR Format ID.
        /// </summary>
        internal static string TITLE_FORMAT_ID {
            get {
                return ResourceManager.GetString("TITLE_FORMAT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Code.
        /// </summary>
        internal static string TITLE_KEY_CODE {
            get {
                return ResourceManager.GetString("TITLE_KEY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key ID.
        /// </summary>
        internal static string TITLE_KEY_ID {
            get {
                return ResourceManager.GetString("TITLE_KEY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Name.
        /// </summary>
        internal static string TITLE_KEY_NAME {
            get {
                return ResourceManager.GetString("TITLE_KEY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote ID.
        /// </summary>
        internal static string TITLE_REMOTE_ID {
            get {
                return ResourceManager.GetString("TITLE_REMOTE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized Format.
        /// </summary>
        internal static string UNRECOGNIZED_FORMAT {
            get {
                return ResourceManager.GetString("UNRECOGNIZED_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up {
            get {
                object obj = ResourceManager.GetObject("up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting IR signal.
        /// </summary>
        internal static string WAITING_IR_SIGNAL {
            get {
                return ResourceManager.GetString("WAITING_IR_SIGNAL", resourceCulture);
            }
        }
    }
}
